namespace WinGetStore.WinRT
{
    [default_interface]
    [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 1)]
    static runtimeclass WinGetProjectionFactory
    {
        static Boolean IsUseDev { get; set; };
        static Boolean IsWinGetInstalled { get; };
        static Boolean IsWinGetDevInstalled { get; };

        static Microsoft.Management.Deployment.PackageManager CreatePackageManager();
        static Microsoft.Management.Deployment.FindPackagesOptions CreateFindPackagesOptions();
        static Microsoft.Management.Deployment.CreateCompositePackageCatalogOptions CreateCreateCompositePackageCatalogOptions();
        static Microsoft.Management.Deployment.InstallOptions CreateInstallOptions();
        [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 4)]
        static Microsoft.Management.Deployment.UninstallOptions CreateUninstallOptions();
        static Microsoft.Management.Deployment.PackageMatchFilter CreatePackageMatchFilter();
        [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 7)]
        static Microsoft.Management.Deployment.DownloadOptions CreateDownloadOptions();
        [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 4)]
        static Microsoft.Management.Deployment.PackageManagerSettings CreatePackageManagerSettings();

        static Microsoft.Management.Deployment.PackageManager TryCreatePackageManager();
        static Microsoft.Management.Deployment.FindPackagesOptions TryCreateFindPackagesOptions();
        static Microsoft.Management.Deployment.CreateCompositePackageCatalogOptions TryCreateCreateCompositePackageCatalogOptions();
        static Microsoft.Management.Deployment.InstallOptions TryCreateInstallOptions();
        [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 4)]
        static Microsoft.Management.Deployment.UninstallOptions TryCreateUninstallOptions();
        static Microsoft.Management.Deployment.PackageMatchFilter TryCreatePackageMatchFilter();
        [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 7)]
        static Microsoft.Management.Deployment.DownloadOptions TryCreateDownloadOptions();
        [contract(Microsoft.Management.Deployment.WindowsPackageManagerContract, 4)]
        static Microsoft.Management.Deployment.PackageManagerSettings TryCreatePackageManagerSettings();
    }
}
